# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: acbf3c1534849730c0c0df7eeeedfbd42c355fbc4bfae625bb5281dce87a157588f5d04eb55619bc18af1ca48fd11470dc3b14d9ec81dd7059a5df4fbe1e604e

test:
  secret_key_base: c2bd051bc32046155deacfc71a4bf5ce28d2108428017dae87443a72a29d257086e3db00206a5d01db7ab441de316bf0ec50212d0ecd3ea47c34c789005a88f3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
